### ISSUE TITLE
Improve restore_pref() from prefs module

### ISSUE THREAD

**Issue by whimboo** [mozilla/firefox-greenlight-tests#16]
The restore_pref() method inside the prefs module is not particular helpful at the moment in terms that it can cause lots of race conditions. This will happen when a test is setting this pref multiple times through its life. Then the original value is no longer available. 

What we should do is to add a null check, and only set it if it hasn't been set before.

**Comment by chmanchester** [comment]
#39 takes care of this.

**Comment by whimboo** [comment]
This is not done yet as long as Pull #40 has not landed. Reopening.

**Comment by whimboo** [comment]
PR #40 has been merged.
